name: tests

on:
  push:
   branches:
   - main
  pull_request:
   branches:
   - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.12]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Run Tox
        run: |
          if [[ "${{ matrix.python-version }}" == "3.9" ]]; then
            tox -e py39,static
          elif [[ "${{ matrix.python-version }}" == "3.12" ]]; then
            tox -e py312,static
          fi
